import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

/**
 * Vite config — mobile-first dev server. The client talks to the API server
 * cross-origin via `VITE_API_URL` (configured in `.env`). The session cookie
 * is `SameSite=Strict; HttpOnly; Secure` (set by the server), and axios is
 * configured with `withCredentials: true`, so the browser sends the cookie
 * back on every authenticated request as long as the API CORS config includes
 * the dev origin in `CLIENT_ORIGIN` and `Access-Control-Allow-Credentials`.
 *
 * No `/api` proxy here — the server mounts routes at `/auth`, `/vocab`, ...
 * directly, not under `/api`. A proxy that rewrites would just hide the real
 * URL shape from devtools without adding anything.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * PWA layer (vite-plugin-pwa). Correct-by-construction here — the service
 * worker only emits in a production `vite build`, so it is NOT exercised by
 * the dev server, tests, or this sandbox. Verify at deploy: Lighthouse PWA/a11y
 * 90+, offline shell, and a real install prompt on a served build.
 *
 * Manifest single source: the PLUGIN owns the manifest. The old static
 * `public/manifest.webmanifest` + its `<link rel="manifest">` in index.html
 * were removed so there is exactly one manifest source — the `manifest` object
 * below, which the plugin emits as `manifest.webmanifest` and injects a
 * `<link>` for at build time. (The no-flash theme bootstrap + apple-touch-icon
 * + theme-color metas in index.html are unrelated and stay.)
 *
 * ⚠ SECURITY — the SW must NEVER cache authenticated cross-origin API
 * responses. The API is a *different origin* reached via `VITE_API_URL` with
 * credentialed (cookie) requests. Workbox precache + `navigateFallback` are
 * scoped to the SAME-ORIGIN app shell + static assets only; the glob patterns
 * match build output, never network API calls, and there is deliberately NO
 * `runtimeCaching` entry for the API origin. A cross-origin credentialed
 * fetch therefore falls straight through to the network — the SW never sees,
 * stores, or replays it. `navigateFallbackDenylist` additionally keeps SPA
 * navigation fallback from ever shadowing a path, even though the API is
 * cross-origin and out of the SW's navigation scope to begin with.
 */
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // 'prompt': a new SW installs but WAITS. The app surfaces a persistent
      // "new version — reload" banner (PwaUpdatePrompt); only when the user taps
      // it does the SW skipWaiting() and the page reload onto the fresh bundle —
      // deterministically, in one reload. This replaces the old 'autoUpdate',
      // which updated silently on the *next* visit (so an open tab kept the stale
      // bundle — the "I don't see the change after deploy" problem) and could
      // 404 a lazy chunk whose hash changed mid-session.
      registerType: 'prompt',
      // Registration is owned by useRegisterSW() inside PwaUpdatePrompt (so we
      // get the onNeedRefresh hook) — do NOT also auto-inject a registration.
      injectRegister: null,
      // Do NOT run the SW in dev — avoids stale-cache surprises while iterating
      // and keeps the dev server / Vitest from registering a worker.
      devOptions: { enabled: false },
      // Plugin generates the SW (generateSW/Workbox mode — the default).
      manifest: {
        name: '한국어 마스터 — Korean Master',
        short_name: '한국어 마스터',
        description:
          'Hanji-paper Korean study app for TOPIK II Level 4. Read, review, drill, and bank vocabulary tapped from real text.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#E8DFC5',
        theme_color: '#E8DFC5',
        lang: 'ko',
        categories: ['education', 'books'],
        icons: [
          // SVG first as a scalable `any` fallback (kept from the original
          // manifest). Raster PNGs (generated by scripts/generate-pwa-icons.mjs)
          // satisfy Android/Chrome install criteria + iOS launcher.
          {
            src: '/favicon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
            purpose: 'any',
          },
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          // Maskable variant (20% safe-zone padding) so Android adaptive icons
          // don't clip the seal under a circular/rounded mask.
          {
            src: '/maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Precache the same-origin app shell + static assets. These globs match
        // BUILD OUTPUT under dist/ only — never API network responses.
        globPatterns: ['**/*.{js,css,html,svg,woff2,png}'],
        // SPA fallback: client-side routes (e.g. /reading, /settings, /topik,
        // /grammar) that the static server doesn't know about resolve to the
        // app shell. These ARE app routes and SHOULD fall back — they are NOT
        // API paths (the API is a separate cross-origin host via VITE_API_URL).
        navigateFallback: '/index.html',
        // Defense-in-depth only. The API is cross-origin, so the SW never
        // intercepts its requests and these patterns are not app routes. But if
        // the API were ever same-origin'd behind a reverse proxy under these
        // prefixes, navigation to them must hit the network, never the cached
        // index.html. We deliberately do NOT list app route prefixes here
        // (/topik, /grammar, /hanja, /reference, ...) — those must fall back.
        navigateFallbackDenylist: [/^\/api\//, /\/[^/?]+\.[^/?]+$/],
        // No `runtimeCaching` entry: there is intentionally NO caching rule for
        // the cross-origin credentialed API. Authenticated responses are never
        // stored or replayed by the SW.
      },
    }),
  ],
  server: {
    port: Number.parseInt(process.env.PORT ?? '4173', 10),
    host: '0.0.0.0',
  },
});
