/**
 * Tests for src/services/storyImage.ts (F-211 — the in-server illustration
 * job runner). storyAudio.test.ts's structure with the provider swapped:
 * driven DETERMINISTICALLY — no timers — each test calls runStoryImageTick
 * directly with an injected ImageGenProvider (setImageGenProvider) and the
 * suite's stub Claude proxy (generateStoryImagePrompts), against a real
 * Postgres (testcontainers) and a throwaway blob-store temp dir
 * (IMAGE_STORAGE_DIR env-injected before buildTestApp).
 *
 * Coverage:
 *   - tick, empty queue → 'idle'
 *   - happy path → job 'done' + N story_images rows (correct image_number
 *     order, the prompt-set's exact scene prompts persisted, dimensions)
 *     + N blobs on disk with the exact generated bytes — all committed
 *     atomically; sceneCount follows the job's image_count snapshot
 *   - ALL-OR-NOTHING: an image failure mid-set → job 'failed' with the
 *     provider's whitelisted message; NO rows; EVERY blob the run wrote is
 *     unlinked (never 2 of 3 images)
 *   - prompt-step (Claude) failure → job 'failed' with the GENERIC message
 *     (proxy internals never reach the user-visible error); no provider
 *     call, no rows, no blobs
 *   - persist failure (generate-once unique tripped) → rollback: job
 *     'failed', only the pre-existing rows remain, fresh blobs unlinked
 *   - an unsupported provider mime → 'failed' generic, nothing written
 *   - malformed stored turns → the job still succeeds WITH a warn log
 *     (mirrors the audio runner's visible-degrade contract)
 *   - stale-'running' reap: an old running job is settled 'failed';
 *     'pending' is never reaped; a YOUNG running job is left alone
 */
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { startPostgres, stopPostgres, type PgHandle } from '../helpers/pg.js';
import { buildTestApp, makeStubProxy, teardownTestApp, type TestApp } from '../helpers/app.js';
import {
  registerUser,
  seedGeneratedStory,
  seedStoryImageJob,
  seedStoryImages,
} from '../helpers/seed.js';
import { runStoryImageTick } from '../../src/services/storyImage.js';
import { _setConfigForTesting, loadConfig } from '../../src/config/index.js';
import {
  ImageGenUpstreamError,
  resetImageGenProviderForTesting,
  setImageGenProvider,
  type ImageGenProvider,
} from '../../src/services/imageGen.js';
import { setClaudeProxy } from '../../src/services/claudeProxy.js';
import { getLogger } from '../../src/logging.js';

let pg: PgHandle;
let t: TestApp;

const PNG_BYTES = Buffer.from('fake-png-bytes-for-story-image-test');

/** A provider that records every prompt. `failAtCall` (1-based) makes exactly
 *  that call throw a whitelisted upstream error. Image bytes = PNG_BYTES +
 *  the utf8 prompt, so each scene's bytes are deterministic per prompt. */
function recordingProvider(
  prompts: string[],
  opts: { failAtCall?: number; mimeType?: string } = {},
): ImageGenProvider {
  let n = 0;
  return {
    generate: async (prompt) => {
      n++;
      if (n === opts.failAtCall) {
        throw new ImageGenUpstreamError(500, 'the image service rejected the request (HTTP 500)');
      }
      prompts.push(prompt);
      return {
        image: Buffer.concat([PNG_BYTES, Buffer.from(prompt, 'utf8')]),
        mimeType: opts.mimeType ?? 'image/png',
        width: 1024,
        height: 1024,
      };
    },
  };
}

/** Files currently under the user's blob dir ([] when the dir doesn't exist). */
async function userBlobFiles(userId: number): Promise<string[]> {
  try {
    return await readdir(path.join(process.env.IMAGE_STORAGE_DIR!, String(userId)));
  } catch {
    return [];
  }
}

beforeAll(async () => {
  process.env.IMAGE_STORAGE_DIR = path.join(
    os.tmpdir(),
    `km-story-image-test-${process.pid}-${Date.now()}`,
  );
  pg = await startPostgres();
  t = buildTestApp({ connectionString: pg.connectionString });
});

afterAll(async () => {
  await teardownTestApp(t);
  await stopPostgres(pg);
  delete process.env.IMAGE_STORAGE_DIR;
});

beforeEach(async () => {
  await pg.pool.query(
    'TRUNCATE TABLE story_image_jobs, story_images, generated_stories, sessions, users RESTART IDENTITY CASCADE',
  );
  // RESTART IDENTITY reuses user ids across tests, but blob FILES survive the
  // TRUNCATE — wipe the store root so "no blob left behind" assertions can
  // never see a previous test's file.
  await rm(process.env.IMAGE_STORAGE_DIR!, { recursive: true, force: true });
  // Re-install the default stub proxy (tests that exercise the prompt-step
  // failure path swap in a throwing stub).
  setClaudeProxy(makeStubProxy());
});

afterEach(() => {
  resetImageGenProviderForTesting();
});

describe('runStoryImageTick', () => {
  it('returns idle when nothing is pending', async () => {
    setImageGenProvider(recordingProvider([]));
    await expect(runStoryImageTick(getLogger())).resolves.toBe('idle');
  });

  it('happy path: claims, generates N scenes, persists rows + blobs atomically, settles done', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId, { title: '고양이 카페' });
    const jobId = await seedStoryImageJob(pg.pool, userId, storyId, {
      status: 'pending',
      imageCount: 3,
    });
    const prompts: string[] = [];
    setImageGenProvider(recordingProvider(prompts));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('done');

    // The stub proxy authored image_count scene prompts embedding the title;
    // the provider saw them in story order.
    expect(prompts).toHaveLength(3);
    expect(prompts[0]).toContain('고양이 카페');
    expect(prompts.map((_, i) => prompts[i]!.startsWith(`mock scene ${i + 1} `))).toEqual([
      true,
      true,
      true,
    ]);

    // Job settled done.
    const job = await pg.pool.query<{
      status: string;
      started_at: Date | null;
      finished_at: Date | null;
      error: string | null;
      image_count: number;
    }>(
      `SELECT status, started_at, finished_at, error, image_count
         FROM story_image_jobs WHERE id = $1`,
      [jobId],
    );
    expect(job.rows[0]!.status).toBe('done');
    expect(job.rows[0]!.started_at).not.toBeNull();
    expect(job.rows[0]!.finished_at).not.toBeNull();
    expect(job.rows[0]!.error).toBeNull();
    expect(job.rows[0]!.image_count).toBe(3); // the enqueue snapshot is the ledger

    // Rows: ordered 1..3, owner-pinned, the EXACT prompts persisted.
    const rows = await pg.pool.query<{
      image_number: number;
      user_id: string;
      blob_ref: string;
      prompt: string;
      width: number;
      height: number;
    }>(
      `SELECT image_number, user_id::text AS user_id, blob_ref, prompt, width, height
         FROM story_images ORDER BY image_number`,
    );
    expect(rows.rows.map((r) => r.image_number)).toEqual([1, 2, 3]);
    expect(rows.rows.map((r) => r.prompt)).toEqual(prompts);
    for (const r of rows.rows) {
      expect(r.user_id).toBe(String(userId));
      expect(r.width).toBe(1024);
      expect(r.height).toBe(1024);
    }

    // Blobs: one file per scene with the exact generated bytes.
    expect(await userBlobFiles(userId)).toHaveLength(3);
    for (const r of rows.rows) {
      const onDisk = await readFile(path.join(process.env.IMAGE_STORAGE_DIR!, r.blob_ref));
      expect(
        Buffer.compare(onDisk, Buffer.concat([PNG_BYTES, Buffer.from(r.prompt, 'utf8')])),
      ).toBe(0);
      expect(r.blob_ref.endsWith('.png')).toBe(true);
    }
  });

  it("the job's image_count snapshot drives the scene count (2 → 2 rows)", async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending', imageCount: 2 });
    const prompts: string[] = [];
    setImageGenProvider(recordingProvider(prompts));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('done');
    expect(prompts).toHaveLength(2);
    const rows = await pg.pool.query(`SELECT image_number FROM story_images`);
    expect(rows.rows).toHaveLength(2);
  });

  it('ALL-OR-NOTHING: a failure at scene 2 of 3 → job failed (whitelisted message), NO rows, NO blobs', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    const jobId = await seedStoryImageJob(pg.pool, userId, storyId, {
      status: 'pending',
      imageCount: 3,
    });
    const prompts: string[] = [];
    setImageGenProvider(recordingProvider(prompts, { failAtCall: 2 }));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('failed');

    expect(prompts).toHaveLength(1); // stopped at the failure
    const job = await pg.pool.query<{ status: string; error: string | null }>(
      `SELECT status, error FROM story_image_jobs WHERE id = $1`,
      [jobId],
    );
    expect(job.rows[0]!.status).toBe('failed');
    expect(job.rows[0]!.error).toContain('HTTP 500');
    // The partial-failure policy: scene 1's blob was written and must be
    // GONE — a story is never left with a partial image set.
    const rows = await pg.pool.query(`SELECT id FROM story_images`);
    expect(rows.rows).toHaveLength(0);
    expect(await userBlobFiles(userId)).toHaveLength(0);

    // A failed job frees the live slot: a new pending job for the same story
    // is insertable (the partial unique covers only pending/running).
    await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending' });
  });

  it('a prompt-step (Claude) failure → job failed with the GENERIC message; provider never called', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    const jobId = await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending' });
    setClaudeProxy(
      makeStubProxy({
        generateStoryImagePrompts: async () => {
          throw new Error('schema diff: expected scenePrompts — internal detail');
        },
      }),
    );
    const prompts: string[] = [];
    setImageGenProvider(recordingProvider(prompts));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('failed');

    expect(prompts).toHaveLength(0);
    const job = await pg.pool.query<{ status: string; error: string | null }>(
      `SELECT status, error FROM story_image_jobs WHERE id = $1`,
      [jobId],
    );
    expect(job.rows[0]!.status).toBe('failed');
    // Proxy internals must never reach the user-visible job error.
    expect(job.rows[0]!.error).toBe('illustration generation failed unexpectedly — try again later');
    expect(await userBlobFiles(userId)).toHaveLength(0);
  });

  it('persist failure (generate-once unique tripped) → rollback, job failed, fresh blobs unlinked', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    // The story is ALREADY illustrated (per-slot unique will reject a second
    // set) but a pending job somehow exists — the runner must fail the job
    // cleanly, leave exactly the pre-existing rows, and unlink every blob it
    // wrote.
    await seedStoryImages(pg.pool, userId, storyId, { count: 3 });
    const jobId = await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending' });
    setImageGenProvider(recordingProvider([]));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('failed');

    const job = await pg.pool.query<{ status: string; error: string | null }>(
      `SELECT status, error FROM story_image_jobs WHERE id = $1`,
      [jobId],
    );
    expect(job.rows[0]!.status).toBe('failed');
    expect(job.rows[0]!.error).toBe('illustration generation failed unexpectedly — try again later');

    const rows = await pg.pool.query<{ prompt: string }>(
      `SELECT prompt FROM story_images ORDER BY image_number`,
    );
    expect(rows.rows).toHaveLength(3); // only the pre-existing set
    expect(rows.rows[0]!.prompt).toContain('seeded scene');
    // The blobs the runner wrote for the rolled-back persist were unlinked
    // (the seeded rows' blob_refs never existed on disk).
    expect(await userBlobFiles(userId)).toHaveLength(0);
  });

  it('an unsupported provider mime → job failed generic, nothing written', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    const jobId = await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending' });
    setImageGenProvider(recordingProvider([], { mimeType: 'image/tiff' }));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('failed');
    const job = await pg.pool.query<{ status: string; error: string | null }>(
      `SELECT status, error FROM story_image_jobs WHERE id = $1`,
      [jobId],
    );
    expect(job.rows[0]!.status).toBe('failed');
    expect(job.rows[0]!.error).toBe('illustration generation failed unexpectedly — try again later');
    expect(job.rows[0]!.error).not.toContain('tiff');
    const rows = await pg.pool.query(`SELECT id FROM story_images`);
    expect(rows.rows).toHaveLength(0);
    expect(await userBlobFiles(userId)).toHaveLength(0);
  });

  it('MALFORMED stored turns degrade visibly (warn log) and the job still succeeds', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId, {
      turns: [{ speaker: '민수' }], // array (passes 081's CHECK) but schema-invalid
    });
    await seedStoryImageJob(pg.pool, userId, storyId, { status: 'pending', imageCount: 2 });
    setImageGenProvider(recordingProvider([]));
    const logger = getLogger();
    const warnSpy = vi.spyOn(logger, 'warn');

    try {
      await expect(runStoryImageTick(logger)).resolves.toBe('done');
      // The degrade is silent to the USER but never to the logs (the audio
      // runner's exact contract).
      expect(
        warnSpy.mock.calls.some((c) => String(c[1]).includes('turns present but unparseable')),
      ).toBe(true);
    } finally {
      warnSpy.mockRestore();
    }
    const rows = await pg.pool.query(`SELECT id FROM story_images`);
    expect(rows.rows).toHaveLength(2);
  });

  it('reaps a stale running job as failed; a fresh pending job still runs', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const staleStory = await seedGeneratedStory(pg.pool, userId);
    const staleId = await seedStoryImageJob(pg.pool, userId, staleStory, {
      status: 'running',
      startedAt: new Date(Date.now() - 60 * 60 * 1000), // 1h ago ≫ 15min threshold
    });
    const freshStory = await seedGeneratedStory(pg.pool, userId);
    // A FRESH pending job — old created_at must NOT get it reaped ('pending'
    // is the healthy backlog); the tick claims and runs it normally.
    const pendingId = await seedStoryImageJob(pg.pool, userId, freshStory, {
      status: 'pending',
      createdAt: new Date(Date.now() - 60 * 60 * 1000),
    });
    setImageGenProvider(recordingProvider([]));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('done');

    const rows = await pg.pool.query<{ id: string; status: string; error: string | null }>(
      `SELECT id::text AS id, status, error FROM story_image_jobs ORDER BY id`,
    );
    const stale = rows.rows.find((r) => r.id === String(staleId))!;
    expect(stale.status).toBe('failed');
    expect(stale.error).toContain('interrupted');
    const pending = rows.rows.find((r) => r.id === String(pendingId))!;
    expect(pending.status).toBe('done');
  });

  it('Phase 1.3: the idle color reaps stale jobs but never claims pending ones', async () => {
    // Blue/green gating (audit §7.2): when this process is NOT the active
    // color, the tick must still reap (time-based, benign in every color)
    // but must NOT claim + process pending work — that belongs solely to the
    // color nginx is actively routing to.
    const { userId } = await registerUser(t.app, pg.pool);
    const staleStory = await seedGeneratedStory(pg.pool, userId);
    const staleId = await seedStoryImageJob(pg.pool, userId, staleStory, {
      status: 'running',
      startedAt: new Date(Date.now() - 60 * 60 * 1000), // 1h ago ≫ 15min threshold
    });
    const pendingStory = await seedGeneratedStory(pg.pool, userId);
    const pendingId = await seedStoryImageJob(pg.pool, userId, pendingStory, {
      status: 'pending',
    });
    setImageGenProvider(recordingProvider([]));

    const otherColorDir = await mkdtemp(
      path.join(os.tmpdir(), 'km-story-image-active-color-'),
    );
    const otherColorFile = path.join(otherColorDir, 'active-color');
    await writeFile(otherColorFile, 'green\n');
    // Snapshot the whole config and restore it verbatim afterward (rather
    // than resetting to `{}`) — `_setConfigForTesting` re-parses process.env
    // fresh under the hood, which would silently drop buildTestApp's own
    // overrides (MFA_REQUIRED/REGISTRATION_ENABLED/etc.) for every test that
    // runs after this one in the same file.
    const prevCfg = loadConfig();
    _setConfigForTesting({
      ...prevCfg,
      DEPLOY_COLOR: 'blue',
      ACTIVE_COLOR_FILE: otherColorFile,
    });
    try {
      // 'idle', not 'done' — claim+process never ran, even though a pending
      // job was available and would normally have been claimed immediately.
      await expect(runStoryImageTick(getLogger())).resolves.toBe('idle');
    } finally {
      _setConfigForTesting(prevCfg);
    }

    const rows = await pg.pool.query<{ id: string; status: string }>(
      `SELECT id::text AS id, status FROM story_image_jobs ORDER BY id`,
    );
    // Reap still ran despite the gate.
    expect(rows.rows.find((r) => r.id === String(staleId))!.status).toBe('failed');
    // Claim never ran: the pending job is untouched.
    expect(rows.rows.find((r) => r.id === String(pendingId))!.status).toBe('pending');
  });

  it('a YOUNG running job is neither reaped nor re-claimed', async () => {
    const { userId } = await registerUser(t.app, pg.pool);
    const storyId = await seedGeneratedStory(pg.pool, userId);
    await seedStoryImageJob(pg.pool, userId, storyId, {
      status: 'running',
      startedAt: new Date(),
    });
    setImageGenProvider(recordingProvider([]));

    await expect(runStoryImageTick(getLogger())).resolves.toBe('idle');
    const job = await pg.pool.query<{ status: string }>(`SELECT status FROM story_image_jobs`);
    expect(job.rows[0]!.status).toBe('running');
  });
});
